iso <- read.table("liver_isoform_3",head=F,sep="\t",stringsAsFactors=F)
### specify the input file here. Generated by isoform_RefSeq.pl


   ID <- names(table(iso[,1]))

   for(iii in  ID) 
   {
      sub <- iso[iso[,1]== iii, ]
      infor <- sub[1,]
      tot <- sub[-1,]
     if(sum(tot[,6])>1000) ### specifiy the threshold for the total number of mapped short-reads for each gene 
     {  if(infor[1,3]=="+")
      {tot <- tot[nrow(tot):1,]} 
      name <- strsplit(infor[1,7],",")[[1]]
      INDEX <- matrix(0,nrow=nrow(tot),ncol=length(name))
      DIST <- matrix(0,nrow=nrow(tot),ncol=length(name))
      NM <- matrix(0,nrow=nrow(tot),ncol=length(name))
      lexon <- rep(0,nrow(tot))
      exon_c <- rep(0,nrow(tot))
      for(k in 1:nrow(tot))
      {
          INDEX[k,] <- as.numeric(strsplit(tot[k,7],",")[[1]])
          exon_c[k] <- tot[k,6]
          lexon[k] <- (tot[k,5]-tot[k,4] + 1)
          if(k==1)
          {DIST[k,] <- lexon[k] * INDEX[k,]/2  }
          if(k>1)    
          {DIST[k,] <- INDEX[k,] * (lexon[1:k]%*% INDEX[1:k,] - lexon[k] * INDEX[k,]/2)}
      }
      for(k in 1:length(name)) #normalized distance 
      {
          DIST[,k] <- DIST[,k]/sum(lexon*INDEX[,k])
      }

      ### EM  
      alpha  <- 0
      theta  <- rep(1/length(name),length(name))
      for(iter in 1:1000)  
      {     ## E-Step
            EEE  <-  exp(-alpha*DIST) 
            for(k in 1:nrow(tot))
            {  eeek <- sum(INDEX[k,]*theta*EEE[k,])
               if(!is.na(eeek) && ( eeek> 1e-12))
               {NM[k,] <- exon_c[k]*(INDEX[k,]*theta*EEE[k,])/eeek}
               else
               {NM[k,] <- rep(0,length(name))}
            }
            ## M-Step
                a <- alpha
                for(n in 1:10)
                {
                    eee  <-  exp(-a*DIST)
                    D0 <- lexon %*% (INDEX*eee) 
                    D1 <- lexon %*% (INDEX*eee*DIST)
                    D2 <- lexon %*% (INDEX*eee*DIST^2)
                    TI <- apply(INDEX*NM,2,sum)
                    First <-  -sum(INDEX*NM*DIST)  
                    Second <- 0   
                    for(ttt in 1:ncol(NM))
                    {
                       First  <- First+TI[ttt]*(D1[ttt]/D0[ttt]) 
                       Second <- Second +TI[ttt]*((D1[ttt]^2-D0[ttt]*D2[ttt])/D0[ttt]^2)            
                    }
                    a <- a - First/Second  
                }   
                alpha <- a 
                EEE <- exp(-alpha*DIST)
                WWW <- lexon %*% (INDEX*EEE)    
                BBB <- (apply(INDEX*NM,2,sum)/sum(exon_c))/WWW
                theta <- BBB/sum(BBB)
               #  print(c(alpha,theta))
      } ## EM Iteration
  
      ot <- c(iii,name,theta)  
      write(ot, file = "ex.data", append = T, sep = "\t")  #### specify the output file here

     } ## tot >? 
   } ## 



